"""Constants for the cofybox_packages integration."""

DOMAIN = "cofybox_packages"
NIBE = "Nibe F Series Heat Pump"
VIESSMANN = "Viessmann Heat Pump"
VICTRON = "Victron Battery"
EMONCMS = "EmonCMS"
EMONEVSE = "EmonEVSE"
SUNNYBOY_PV = "SunnyBoy PV"
SUNNYBOY_BATTERY = "SunnyBoy Battery"
SGREADY = "SGReady Heat Pump"
SONNEN = "Sonnen Battery"
SHELLY_METER = "Shelly on Utility Meter"
SHELLY_HEATER = "Shelly on Immersion Heater"
SUNNYBOY_PV_AUTO = "SunnyBoy PV Auto"
SUNNYBOY_PV_MANUAL = "SunnyBoy PV Manual"
SUNNYBOY_BATTERY_AUTO = "SunnyBoy Battery Auto"
SUNNYBOY_BATTERY_MANUAL = "SunnyBoy Battery Manual"
SHELLY_METER_PATH = "/config/library/meter_shelly.yaml"
SHELLY_HEATER_PATH = "/config/library/heater_shelly.yaml"
